linters:
  presets:
    - bugs
    - performance
    - unused
  disable:
    - wsl
    - gochecknoglobals
    - gochecknoinits
    - funlen
    - goconst
    - stylecheck
    - unconvert
    - errorlint
    - gosec
    - perfsprint
    - unparam
    - prealloc

linters-settings:
  gocritic:
    disabled-checks:
      - dupSubExpr
      - ifElseChain
  exhaustive:
    default-signifies-exhaustive: true
