export const enum Class {
    Controls_Disabled = "controls--disabled",
    ControlsButton_Disabled = "controls__button--disabled",
    DirEntry = "dir__entry",
    DirEntry_Playing = "dir__entry--playing",
    DirIcon = "dir__icon",
    DirIcon_Playing = "dir__icon--playing",
    DirLink = "dir__link",
    DirLink_Aux = "dir__link--aux",
    DirListing = "dir__listing",
    Hidden = "hidden",
    MainDir = "main__dir",
    MaterialIcons = "material-icons",
    ModalOverlay = "modal-overlay",
    UiEntryInput_Error = "ui__entry-input--error",
}
