export const enum Class {
    Controls_Disabled = "controls--disabled",
    ControlsButton_Disabled = "controls__button--disabled",
    DirRow = "dir__row",
    DirRow_Playing = "dir__row--playing",
    DirIcon = "dir__icon",
    DirIcon_Playing = "dir__icon--playing",
    DirLink = "dir__link",
    DirLink_Aux = "dir__link--aux",
    DirCellArtist = "dir__cell-artist",
    DirCellDetail = "dir__cell-detail",
    DirCellDuration = "dir__cell-duration",
    DirCellNum = "dir__cell-num",
    DirDiscHeader = "dir__disc-header",
    DirList = "dir__list",
    DirTrackList = "dir__track-list",
    Hidden = "hidden",
    MainDir = "main__dir",
    MaterialIcons = "material-icons",
    ModalOverlay = "modal-overlay",
    SearchInput = "search__input",
    SearchResults = "search__results",
    SearchResult = "search__result",
    SearchResult_Focused = "search__result--focused",
    SearchResultDetail = "search__result-detail",
    UiEntryInput_Error = "ui__entry-input--error",
}
